### ISSUE TITLE
object 'lit' is not exported by 'namespace:SparkR'

### ISSUE THREAD

**Issue by konradzdeb** [SKKU-SKT/ggplot2.SparkR#12]
The installation returns error:
```r
object 'lit' is not exported by 'namespace:SparkR'
```
I tried again loading `SparkR`:

```r
library(SparkR, lib.loc = c(file.path(Sys.getenv("SPARK_HOME"), "R", "lib")))
```
and received the same error, I've SparkR **1.4.1**:

```r
sessionInfo()$otherPkgs$SparkR
Package: SparkR
Type: Package
Title: R frontend for Spark
Version: 1.4.1
(...)
```
---
**Update:**
I've loaded version **1.6.3** and received the same error.

**Comment by JonghyunBae** [comment]
Hi. This problem is occured because of old verison of SparkR.
SparkR ver. 1.4.1 does not support "lit" operation.
So please upgrade your SparkR version (ver. 1.5.0 or later version)

**Comment by JonghyunBae** [comment]
I will check it and report about the result ASAP. 
Thanks.

**Comment by JonghyunBae** [comment]
Could you test one more time to install ggplot2.SparkR?

Now, there is nothing error in my environment.

**Comment by konradzdeb** [comment]
Hi, thanks for looking into this. I had a look again I think I know what's going on. 
### Clean installation
When I attempt to install it *without* loading `SparkR` initially it fails with the following message:
```r
>> devtools::install_github("SKKU-SKT/ggplot2.SparkR")
Downloading GitHub repo SKKU-SKT/ggplot2.SparkR@master
from URL https://api.github.com/repos/SKKU-SKT/ggplot2.SparkR/zipball/master
Installing ggplot2.SparkR
Downloading GitHub repo apache/spark@v1.4.1
(...)

* installing *source* package 'SparkR' ...
** R
** inst
** tests
** preparing package for lazy loading
Creating a new generic function for 'na.omit' in package 'SparkR'
Creating a new generic function for 'filter' in package 'SparkR'
Creating a new generic function for 'intersect' in package 'SparkR'
(...)

* installing *source* package 'ggplot2.SparkR' ...
** R
** preparing package for lazy loading
Error : object 'lit' is not exported by 'namespace:SparkR'
(...)
```

### Second attempt
So if I load the `SparkR` by hand:
```r
>> library(SparkR, lib.loc = "/correct path")

Attaching package: 'SparkR'

The following objects are masked from 'package:stats':

    cov, filter, lag, na.omit, predict, sd, var

The following objects are masked from '.env':

    n, size

The following objects are masked from 'package:base':

    colnames, colnames<-, endsWith, intersect, rank, rbind, sample,
    startsWith, subset, summary, table, transform

>> sessionInfo()$otherPkgs$SparkR
Package: SparkR
Type: Package
Title: R frontend for Spark
Version: 1.6.3
(...)
```

It fails with the same message, ***however*** the loaded `SparkR` version is **1.4.1**, not the **1.6.3**  that I have loaded manually:

```r
>> sessionInfo()$otherPkgs$SparkR
Package: SparkR
Type: Package
Title: R frontend for Spark
Version: 1.4.1
(...)
```

---
Hence the question, I load my `SparkR` via:

```r
library(SparkR, lib.loc = "/correct path")
```

I'm guessing that at some point the package installation is calling `library(SparkR)` / `require(SparkR)`, this results in `SparkR` **1.4.1** being loaded. Is there a way I could install this package with using `SparkR` that I usually load via `library(SparkR, lib.loc = "/correct path")` ?

**Comment by JonghyunBae** [comment]
You can change your R library path in your R environment configuration file.
It you use deb linux (Ubuntu...), you can add your SparkR lib path in '/etc/R/Renviron'.
In that file, you can add your SparkR path in R_LIBS_SITE environment variable.

**Comment by konradzdeb** [comment]
OK, I think that closes this issue. I may force the more recent `SparkR` load just for the purpose of installing this package.
